//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameFrame.rc
//
#define IDC_BT_TITLE_GAMEPHOTO          700
#define IDC_BT_TITLE_GAMEHOME           701
#define IDC_BT_TITLE_GAMESHOP           702
#define IDC_BT_TITLE_GAMESERVER         703
#define IDC_CHAT_MESSAGE                1004
#define IDC_VOR_SPLITER                 1039
#define IDC_SEND_CHAT                   1046
#define IDC_EXPRESSION                  1047
#define IDC_PHRASE                      1048
#define IDC_COLOR_SET                   1049
#define IDC_CLEAN_SCREEN                1050
#define IDC_BUGLE                       1051
#define IDC_USER_LIST                   1056
#define IDC_CHAT_OBJECT                 1068
#define IDB_BT_USERIMAGE_0              4464
#define IDB_BT_USERIMAGE_1              4465
#define IDB_BT_USERIMAGE_2              4466
#define IDB_BT_USERIMAGE_3              4467
#define IDB_BT_USERIMAGE_4              4468
#define IDB_BT_USERIMAGE_5              4469
#define IDB_BT_USERIMAGE_6              4470
#define IDB_BT_USERIMAGE_7              4471
#define IDB_BT_USERIMAGE_8              4472
#define IDB_BT_USERIMAGE_9              4473
#define IDB_BT_DJ_RIGHT                 5000
#define IDB_BT_DJ_LEFT                  5001
#define IDB_BT_DJ_SET                   5002
#define IDB_BT_DJ_HELP                  5003
#define IDB_BT_DJ_CITY                  5004
#define IDB_IMAGE_DOWN_BACK             5365
#define IDB_BT_LIGHT_UP                 5366
#define IDB_BT_UP                       5367
#define IDB_BT_DOWN                     5368
#define IDB_IMAGE_HONG                  7000
#define IDB_SCROLL_IMAGE                7500
#define IDD_GAME_FRAME                  8000
#define IDC_CHAT_INPUT                  8000
#define IDC_QUIT_GAME                   8001
#define IDC_GAME_OPTION                 8002
#define IDC_GAME_RULE                   8003
#define IDC_COMBO1                      8004
#define IDC_LOOKON                      8005
#define IDC_CONTROL                     8006
#define IDC_BT_TITLE_MIN                8007
#define IDC_BT_TITLE_SOUND              8008
#define IDC_SEND_MSG                    8009
#define IDC_STATIC_GAME                 8009
#define IDC_EXP_BT                      8010
#define IDC_STATIC_GAME2                8010
#define IDC_STATIC_MUSIC                8010
#define IDD_FRAME_CONTROL               8011
#define IDB_USER_STATUS                 8012
#define IDC_CHARM_VALUE                 8013
#define IDC_GOLD_VALUE                  8014
#define IDC_EXCHANGE_GOLD_VALUE         8015
#define IDC_REMAIN_CHARM_VALUE          8016
#define IDD_SHOWTIMEDJLIST              8017
#define IDD_SHOWDJINFO                  8018
#define IDD_USERINFODLG                 8020
#define IDB_LIST_TL                     8110
#define IDB_LIST_TM                     8111
#define IDB_LIST_TR                     8112
#define IDB_FRAME_BL                    8113
#define IDB_FRAME_BM                    8114
#define IDB_FRAME_BR                    8115
#define IDB_FRAME_LB                    8116
#define IDB_FRAME_LM                    8117
#define IDB_FRAME_LT                    8118
#define IDB_FRAME_RB                    8119
#define IDB_FRAME_RM                    8120
#define IDB_FRAME_RT                    8121
#define IDB_FRAME_TM                    8122
#define IDB_BITMAP1                     8123
#define IDB_FRAME_MM                    8123
#define IDD_INPUT_MSG_DLG               8124
#define IDD_SCORE_VIEW_DLG              8125
#define IDD_DIALOG1                     8126
#define IDD_GAME_TASK_DLG               8126
#define IDD_DIALOG2                     8127
#define IDD_DLG_DJ_GIVE_INFO            8127
#define IDD_DIALOG_GAMESET              8128
#define IDD_DIALOG3                     8129
#define IDD_DIALOG5                     8130
#define IDD_DLG_GAME_LAUGUAGE           8130
#define IDD_DLG_USER_AFFICE             8131
#define IDD_DIALOG4                     8132
#define IDD_DLG_USERACTION              8132
#define IDD_DIALOG8                     8133
#define IDD_SAY_DLG                     8134
#define IDD_DIALOG6                     8135
#define IDD_DLG_TASK_FINISH             8135
#define IDD_DIALOG7                     8136
#define IDD_N                           8136
#define IDD_NEWGIFT                     8136
#define IDD_DLG_GAMEAFFICHE             8140
#define IDC_SOUND                       8901
#define IDC_GAME_OPTION2                8904
#define IDC_UP_TAG                      8908
#define IDC_BT_TITLE_CLOSE              8909
#define IDC_BT_TITLE_MUTESOUND          8910
#define IDC_UP_TAG2                     8911
#define IDC_GAME_QUIT                   8914
#define IDC_INPUT_EDIT_MSG              8924
#define IDB_BT_TITLE_CLOSE              9200
#define IDB_BT_TITLE_MIN                9201
#define IDB_BT_TITLE_SOUND              9202
#define IDB_BT_TITLE_MUTESOUND          9203
#define IDB_ACCEPT_TASK_BACK            14165
#define IDB_BT_ACCEPT_CLOSE             14166
#define IDB_TASK_END_BACK               14167
#define IDB_BT_TASK_END                 14168
#define IDB_BT_TASK_LIGHT               14169
#define IDB_BT_STARTGAME                14465
#define IDB_BT_GOPLAZA                  14466
#define IDB_BT_GOROOM                   14467
#define IDB_BT_STARTGAME_2              20201
#define IDB_BT_GOPLAZA_2                20202
#define IDB_BT_GOROOM_2                 20203
#define IDB_MP_CHANNEL                  24464
#define IDB_MP_CHANNEL_ACTIVE           24465
#define IDB_MP_THUMB                    24466
#define IDB_MP_THUMB_ACTIVE             24467
#define IDB_IMAGE_CHATBACK              60001
#define IDB_BT_EXPRESSION               60002
#define IDB_BT_SENDCHAT                 60003
#define IDB_IMAGE_WNDBACK               60004
#define IDB_DJINFOSHOW_BACK             60005
#define IDB_GAME_DJ_GIVE_INFO           60006
#define IDB_USER_ACTION_BACK_IMAGE      62007
#define IDB_USER_ACTION_FLASH_BK        62108
#define IDB_BT_SHOW_ACTION              62109
#define IDB_BT_USER_ACTION0             63000
#define IDB_BT_USER_ACTION1             63001
#define IDB_BT_USER_ACTION2             63002
#define IDB_BT_USER_ACTION3             63003
#define IDB_BT_USER_ACTION4             63004
#define IDB_BT_USER_ACTION5             63005
#define IDB_BT_USER_ACTION6             63006
#define IDB_BT_USER_ACTION7             63007
#define IDB_BT_USER_ACTION8             63008
#define IDB_BT_USER_ACTION9             63009
#define IDB_BT_USER_ACTION10            63010
#define IDB_BT_USER_ACTION11            63011
#define IDB_BT_USER_ACTION12            63012
#define IDB_BT_USER_ACTION13            63013
#define IDB_BT_USER_ACTION14            63014
#define IDB_BT_USER_ACTION15            63015
#define IDB_BT_USER_ACTION16            63016
#define IDB_BT_USER_ACTION17            63017
#define IDB_BT_USER_ACTION18            63018
#define IDB_BT_USER_ACTION19            63019
#define IDD_DLG_GAME_FLASH              63020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         8009
#define _APS_NEXT_SYMED_VALUE           8020
#endif
#endif
