//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamePlaza.rc
//
#define IDOK2                           3
#define IDC_ALL_REGISTER                4
#define IDC_ALLOW_ADD_MY                5
#define IDC_RE                          6
#define IDC_BTN_RESUME                  7
#define IDC_REGISTER_USER_DOCU          8
#define IDC_AOUTOMATISM_ADD_MY          9
#define IDC_AUTOMATISM_ADD_MY           10
#define IDC_BTN_CLOSE                   11
#define IDC_REGISTER_USER_DOCU2         12
#define IDC_REGISTER_USER_SEX_WOMAN     13
#define IDC_BTN_DEL                     14
#define IDC_REGISTER_USER_SEX_MAN       15
#define IDC_BTN_FRIEND                  16
#define IDC_BTN_STRANGER                17
#define IDC_BTN_BLACKLIST               18
#define IDC_BTN_TEAMES                  19
#define IDM_ABOUTBOX                    100
#define IDD_LOGONLOGO                   101
#define IDD_PLAZADLG                    104
#define IDD_GAMELISTDLG                 105
#define IDD_KEYDIALOG                   106
#define IDD_TABLELIST                   107
#define IDD_TABLE_LIST                  108
#define IDD_SHOWGAMEMSG                 109
#define IDD_SHORT_MESSAGE               110
#define IDD_FIND_USER                   111
#define IDD_DFGDSGS                     113
#define IDD_MANAGER_RIGHT               115
#define IDS_MAIN_TITLE                  129
#define IDD_GAME_ROOM                   130
#define IDS_STRING131                   131
#define IDS_ABOUTBOX                    132
#define IDD_LOGON                       133
#define IDR_MENU                        134
#define IDD_STATUS                      136
#define IDB_CONNECT_STATUS              137
#define IDB_SERVER_LIST_IMAGE           142
#define IDB_USER_STATUS                 144
#define IDD_OPTION                      181
#define IDD_ENTER_TABLE_PASS            182
#define IDD_OPTION_SYSTEM               183
#define IDC_HAND_CUR                    209
#define IDB_TABLE_LOCK                  230
#define IDB_TABLE_READY                 231
#define IDD_SEND_WARNING                262
#define IDD_REGISTER                    266
#define IDD_MANAGER_MESSAGE             267
#define IDD_MANAGER_SERVER              268
#define IDD_USER_INFO                   272
#define IDD_OPTION_TABLE_RULE           273
#define IDD_CUSTOM_FACE                 276
#define IDD_MODIFY_INDIVIDUAL           277
#define IDB_REGIST_BG                   321
#define IDD_GAME_LIST                   323
#define IDB_PLAZA_BG                    324
#define IDR_PNG1                        327
#define IDR_PNG_LOGIN_BACKGROUND        327
#define IDD_ROOM_LIST                   329
#define IDB_ROOM_LIST_BG                330
#define IDB_TABLE_LIST_BG               331
#define IDB_AUTO_QUEUE                  334
#define IDB_BTN_BTN_CHECK               335
#define IDB_REGIST_CANCEL               336
#define IDB_REGIST_OK                   337
#define IDB_REGIST_USER_DOCU            338
#define IDB_FONT                        339
#define IDB_FACE                        340
#define IDB_CHANNEL                     341
#define IDB_FACE2                       342
#define IDB_SEND_MSG                    343
#define IDB_CHAT_LOG                    344
#define IDB_TABLE_LIST_PGUP             345
#define IDD_FRIEND_LIST                 346
#define IDB_TABLE_LIST_PGDN             347
#define IDB_DESPOKEN_TABLE              348
#define IDD_DIALOG_KEY                  349
#define IDB_FRIEND_BACK                 350
#define IDD_DIALOG_TASK                 351
#define IDB_KEY_0                       352
#define IDD_DIALOG_SHOP                 353
#define IDB_KEY_1                       354
#define IDD_DIALOG_DOTEY_BOX            355
#define IDB_KEY_2                       356
#define IDD_DIALOG_SET                  357
#define IDB_KEY_3                       358
#define IDD_GAMELIST_HOT                359
#define IDB_KEY_4                       360
#define IDB_KEY_19                      366
#define IDB_KEY_20                      367
#define IDB_KEY_21                      368
#define IDB_KEY_22                      369
#define IDB_KEY_23                      370
#define IDB_KEY_24                      371
#define IDB_KEY_25                      372
#define IDB_KEY_26                      373
#define IDB_KEY_27                      374
#define IDB_KEY_28                      375
#define IDB_KEY_29                      376
#define IDB_KEY_30                      377
#define IDB_KEY_31                      378
#define IDB_KEY_32                      379
#define IDB_KEY_33                      380
#define IDB_KEY_34                      381
#define IDB_KEY_35                      382
#define IDB_KEY_36                      383
#define IDB_KEY_37                      384
#define IDB_KEY_38                      385
#define IDB_KEY_39                      386
#define IDB_KEY_40                      387
#define IDB_KEY_41                      388
#define IDB_KEY_42                      389
#define IDB_KEY_43                      390
#define IDB_KEY_44                      391
#define IDB_KEY_45                      392
#define IDB_KEY_46                      393
#define IDB_KEY_47                      394
#define IDB_KEY_48                      395
#define IDB_KEY_49                      396
#define IDB_KEY_50                      397
#define IDB_KEY_51                      398
#define IDB_KEY_52                      399
#define IDB_KEY_53                      400
#define IDB_KEY_54                      401
#define IDB_KEY_55                      402
#define IDB_KEY_56                      403
#define IDB_KEY_57                      404
#define IDB_KEY_58                      405
#define IDB_KEY_59                      406
#define IDB_KEY_60                      407
#define IDB_KEY_61                      408
#define IDB_KEY_62                      409
#define IDB_KEY_63                      410
#define IDB_KEY_64                      411
#define IDB_KEY_65                      412
#define IDB_KEY_66                      413
#define IDB_KEY_67                      414
#define IDB_KEY_68                      415
#define IDB_KEY_69                      416
#define IDB_KEY_70                      417
#define IDB_KEY_71                      418
#define IDB_KEY_72                      419
#define IDB_KEY_73                      420
#define IDB_KEY_74                      421
#define IDB_KEY_75                      422
#define IDB_KEY_76                      423
#define IDB_KEY_77                      424
#define IDB_KEY_78                      425
#define IDB_KEY_79                      426
#define IDB_KEY_80                      427
#define IDB_KEY_81                      428
#define IDB_KEY_82                      429
#define IDB_KEY_83                      430
#define IDB_KEY_84                      431
#define IDB_KEY_85                      432
#define IDB_KEY_86                      433
#define IDB_KEY_87                      434
#define IDB_KEY_88                      435
#define IDB_KEY_89                      436
#define IDB_KEY_90                      437
#define IDB_KEY_91                      438
#define IDB_KEY_92                      439
#define IDB_KEY_93                      440
#define IDB_KEY_94                      441
#define IDB_KEY_95                      442
#define IDB_KEY_96                      443
#define IDB_KEY_BACK                    444
#define IDB_KEY_CLOSE                   445
#define IDB_GAME_LIST_BACK              446
#define IDB_SET_DLG_CANCEL              447
#define IDB_SET_DLG_OK                  448
#define IDB_SET_DLG_RESUME              449
#define IDB_SET_BACK                    450
#define IDD_PLAZA_GAME_WEB              700
#define IDB_KEY_5                       701
#define IDD_GAME_LIST_CENTER            702
#define IDB_KEY_6                       703
#define IDB_KEY_7                       704
#define IDB_KEY_8                       705
#define IDB_KEY_9                       706
#define IDD_ROOM_LIST_CENTER            707
#define IDB_KEY_10                      708
#define IDD_PLAZA_CLOSE_CONFIRM         709
#define IDB_KEY_11                      710
#define IDD_CONFIRM_GOLD                720
#define IDB_KEY_12                      721
#define IDD_DIALOG1                     722
#define IDD_CONFIRM_GRADE               723
#define IDB_KEY_13                      724
#define IDB_KEY_14                      725
#define IDB_KEY_15                      726
#define IDB_KEY_16                      727
#define IDB_KEY_17                      728
#define IDB_KEY_18                      729
#define IDD_NEWCOMER_GUIDE              900
#define IDD_GAME_RULE                   901
#define IDD_NEWHANDTASK                 902
#define IDD_ACTIVE                      903
#define IDC_CHAT_MESSAGE                1002
#define IDC_TABLE_PASSWORD              1003
#define IDC_SERVER                      1004
#define IDC_ACCOUNTS                    1005
#define IDC_PASSWORD                    1006
#define IDC_REM_PASSWORD                1007
#define IDC_SPREADER                    1008
#define IDC_DELETE_RECORD               1009
#define IDC_MAIL                        1010
#define IDC_SEND_SHORT                  1011
#define IDC_DELETE_RECORD2              1012
#define IDC_CHECK_PASSWORD              1013
#define IDC_MAIL2                       1014
#define IDC_PASSWORD2                   1015
#define IDC_BIND_USER                   1016
#define IDC_NET_OPTION                  1017
#define IDC_REGISTER                    1018
#define IDC_RECV_MESSAGE                1019
#define IDC_BANK                        1050
#define IDC_LIMIT_SCORE                 1051
#define IDC_USER_LIST                   1052
#define IDC_LIMIT_DETEST                1060
#define IDC_LIMIT_WIN_RATE              1061
#define IDC_WIN_RATE                    1062
#define IDC_SCORE_LESS                  1063
#define IDC_SAVE_NONE                   1065
#define IDC_SAVE_ACCOUNTS               1066
#define IDC_SAVE_ACCOUNTS_AND_PASS      1067
#define IDC_CHAT_OBJECT                 1068
#define IDC_USER_FACE                   1069
#define IDC_PRIVIEW                     1070
#define IDC_WARNING_MESSAGE             1071
#define IDC_ROOM_CHAT                   1072
#define IDC_GAME_MESSAGE                1073
#define IDC_GAME_CHAT                   1074
#define IDC_ROOM_MESSAGE                1075
#define IDC_SEND_WISPER                 1076
#define IDC_SYSTEM_MESSAGE              1077
#define IDC_PLAY_GAME                   1078
#define IDC_LOOKON_GAME                 1079
#define IDC_SET_SHALL_CLOSE             1080
#define IDC_LIMIT_WISPER                1081
#define IDC_RADIO1                      1082
#define IDC_LIMIT_ROOM_CHAT             1083
#define IDC_RADIO2                      1084
#define IDC_BUTTON_GAME_CLIENT          1090
#define IDC_BT_SITE                     1091
#define IDC_RESET_SHALL_CLOSE           1092
#define IDC_BT_RE_LOGON                 1093
#define IDC_ALLOW_WISPER                1094
#define IDC_BT_CHARGE                   1095
#define IDB_BT_DEPOSITORY               1096
#define IDC_ALLOW_ROOM_CHAT             1097
#define IDC_BT_RETURN                   1098
#define IDC_ALLOW_ENTER_GAME            1099
#define IDC_WEBBROWSER1                 1100
#define IDC_BT_CLINET                   1101
#define IDB_BT_SHOP                     1102
#define IDC_EXPLORER1                   1103
#define IDC_BT_RE_ACCOUNTS_MANAGE       1104
#define IDC_BT_AM                       1105
#define IDB_BT_TASK                     1106
#define IDC_BUTTON2                     1107
#define IDC_UPDATE_USERINFO             1107
#define IDC_SPARROWYY                   1107
#define IDC_NEWCOMER_GAMETASK           1107
#define IDC_PGDWON                      1108
#define IDB_BT_DEPOSITORY5              1109
#define IDB_BT_TOOL                     1110
#define IDC_BT_TELECOM                  1111
#define IDC_GAME_LIST                   1112
#define IDC_PLAZA_CLOSE_CONFIRM_RESET_LOGON 1114
#define IDC_CONFIRM_GOLD_OK             1115
#define IDC_BUTTON3                     1116
#define IDC_LANDCRAZY                   1116
#define IDC_NEWCOMER_GAMECURRENCY       1116
#define IDC_EXITMANEGERWINDOW           1116
#define IDC_PGUP                        1117
#define IDC_STATIC_INPUT                1118
#define IDC_STATIC_OUTPUT               1119
#define IDC_BT_TELECOM2                 1120
#define IDC_BT_MESHWORK                 1121
#define IDC_GAME_HELP                   1122
#define IDC_BT_AUTO                     1123
#define IDC_PLAZA_CLOSE_CONFIRM_OVER    1124
#define IDC_AUTO_QUEUE                  1125
#define IDC_CHECK_USER_DOCU             1126
#define IDC_MINSIZE                     1127
#define IDC_EDIT_INPUT                  1128
#define IDC_RICHEDIT2_OUTPUT            1129
#define IDC_PGDWON2                     1130
#define IDB_BT_DESPOKEN_TABLE           1131
#define IDC_COMBO1                      1132
#define IDC_RICHEDIT2_OUTPUT2           1133
#define IDC_STATIC111                   1134
#define IDC_BTN_ADD                     1135
#define IDC_LIST_FRIEND                 1136
#define IDB_BTN_MY_TOOL                 1137
#define IDC_CHECK_BACK_MUSIC            1138
#define IDC_GUIDE                       1138
#define IDC_CHECK_GAME_MUSIC            1139
#define IDC_NEWCOMER_GIFT               1139
#define IDC_CHECK_MAN_MUSIC             1140
#define IDC_NEWCOMER_PRIZEEXCHARGE      1140
#define IDC_CHECK_CARTOON_MUSIC         1141
#define IDC_CONFIRM_GOLD_GETALL         1141
#define IDC_SLIDER1                     1142
#define IDC_SLIDER2                     1143
#define IDC_BT_SEND                     1143
#define IDC_ACCOUNTS_MANAGE             1144
#define IDC_BT_PRIVIEW                  1144
#define IDC_SLIDER3                     1145
#define IDC_BT_CANCEL                   1145
#define IDC_GAME_WEB                    1146
#define IDC_SLIDER4                     1147
#define IDC_CONTACT_SERVISE             1148
#define IDC_TOUNAMENT                   1149
#define IDC_ACCOUNTS_RECHARGE           1150
#define IDC_PRIZE_EXCHARGE              1151
#define IDC_PROPS_SHOP                  1152
#define IDC_NOVICE_TASK                 1153
#define IDC_BACK_PACK                   1154
#define IDC_USER_INFO                   1155
#define IDC_EMAIL_MESSAGE               1156
#define IDC_BT_LOGON_EXIT               1157
#define IDC_PLAZA_ROLLBACK              1158
#define IDC_BUTTON6                     1159
#define IDC_NEWCOMER_GAMEHELP           1159
#define IDC_PLAZA_NEXT_PAGE             1160
#define IDC_GENDER                      1500
#define IDC_LIMIT_ENTER_GAME            1501
#define IDC_RADIO3                      1502
#define IDC_OPEN_CHAT_MESSAGE           1503
#define IDC_BROWSER                     1504
#define IDC_LIMIT_GAME_CHAT             1505
#define IDC_SHOW_INOUT                  1506
#define IDC_HOR_SPLITER                 1507
#define IDC_UPLOAD                      1508
#define IDC_SCORE_MAX                   1509
#define IDC_LIMIT_ENTER_ROOM            1701
#define IDC_ENTER_TABLE_PASSWORD        1702
#define IDC_DELETE                      1703
#define IDC_BUTTON_GETBACK_PASSWORD     1704
#define IDC_WARIMG_MSG                  1705
#define IDC_SPARROWZZ                   1706
#define IDC_BUTTON_VISIT_WEB            1707
#define IDC_SISEQIU                     1707
#define IDC_BT_SHOP                     1708
#define IDC_RETURN                      1709
#define IDC_BT_EXIT                     1720
#define IDC_VISIT_WEB                   1721
#define IDC_PLAZA_CLOSE_CONFIRM_CLOSE   1723
#define IDC_CONFIRM_GOLD_GETGOLD        1724
#define IDC_CONFIRM_GRADE_OK            1725
#define IDC_PLAZA_FACE                  1726
#define IDC_BUTTON_GAME_HELP            1727
#define IDC_BUTTON4                     1728
#define IDC_NEWCOMER_PROPSSHOP          1728
#define IDC_BT_MORE                     1729
#define IDC_QUESTION_FEEDBACK           1730
#define IDC_PLAZA_CLOSE_CONFIRM_CANCEL  1732
#define IDC_GAME_FACE                   1733
#define IDC_BT_BEAUTY_SALON             1734
#define IDC_BUTTON_GAME_SHOP            1735
#define IDC_BT_HONOUR_ROLL              1736
#define IDC_BT_MUSIC                    1800
#define IDB_BT_FRIEND                   1801
#define IDC_BT_RE_LOGON2                1802
#define IDC_BT_RE_GAME_PLAZY            1803
#define IDC_ALLOW_GAME_CHAT             1804
#define IDC_BOSS_HOTKEY                 1805
#define IDC_BT_SET                      1806
#define IDC_ALLOW_ENTER_ROOM            1807
#define IDC_BT_CLOSE                    1808
#define IDC_CUSTOM1                     1809
#define IDC_BIND_GAME                   2100
#define IDC_LOGON_TYPE                  2101
#define IDC_SEND_MESSAGE                2102
#define IDC_NAME                        2103
#define IDC_MAIN_PAGE                   2104
#define IDC_ACCID                       2105
#define IDC_PASSWORD_PROTECT            2106
#define IDC_GET_PASSWORD                2107
#define IDC_REG_WEB                     2108
#define IDC_PROXY_TEST                  2109
#define IDC_PROXY_TYPE                  2200
#define IDC_PROXY_SERVER                2201
#define IDC_PROXY_USER                  2202
#define IDC_PROXY_PORT                  2203
#define IDC_LIST                        2204
#define IDC_PROXY_PASS                  2205
#define IDC_BORDER                      2206
#define IDC_LIST_STRANGER               2207
#define IDC_USER_ID                     2208
#define IDC_LIST_BLACKLIST              2209
#define IDC_CLOSE                       2300
#define IDC_EDIT_PASSWORD3              2301
#define IDC_EDIT_ACCOUNTS               2302
#define IDC_LIST_TEAMES                 2303
#define IDC_TYPE_NAME                   2304
#define IDC_BUTTON_KEY                  2305
#define IDC_BRING_TABLE_PASSWORD        2306
#define IDC_VOR_SPLITER                 2307
#define IDC_CHAT_INPUT                  2308
#define IDC_AUTO_SIT                    2309
#define IDC_SEND_CHAT                   2320
#define IDC_EXPRESSION                  2321
#define IDC_PHRASE                      2322
#define IDC_COLOR_SET                   2323
#define IDC_CLEAN_SCREEN                2324
#define IDC_FIND_USER                   2325
#define IDC_LIMIT_IP                    2326
#define IDC_QUIT_ROOM                   2327
#define IDC_LIMIT_FLEE_RATE             2328
#define IDC_BUGLE                       2329
#define IDC_FLEE_RATE                   2330
#define IDM_CALL_CANCEL_GAME            32763
#define IDM_LOGON_PLAZA                 32772
#define IDM_CONNECT_SERVER              32774
#define IDM_CHECK_LINE					32775
#define IDM_CANCEL_CONNECT              32776
#define IDM_CALL_ROOM_LIST              32778
#define IDM_CALL_GAME_LIST              32780
#define IDM_CALL_TABLE_LIST             32781
#define IDM_CALL_EXIT_GAME              32782
#define IDM_CALL_SHOW_CUSTOMER          32783
#define IDB_DLG_STATUS_BACK             40000
#define IDB_CALL_UPDATE_USERIMAGE       40001
#define IDR_MAINFRAMEICO                40003
#define IDB_ROOM_VIEW_AFFICHE           40004
#define IDB_LOOK_GAME_MSG_MORE          40005
#define IDC_GAME_RULE                   40007
#define IDD_GAME_ROOM_DLG               40008
#define IDC_ENTER_GAME                  40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        902
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           905
#endif
#endif
